const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
const entries=JSON.parse(document.getElementById('collection-data').textContent);
let active=0;
const photo=document.querySelector('.collection-photo');
const caption=document.querySelector('.collection-caption');
function showSlide(delta){active=(active+delta+entries.length)%entries.length;const s=entries[active];photo.src=s.desktop;photo.closest('picture').querySelector('source').srcset=s.mobile;photo.alt=s.title+' 포트폴리오용 연출 사진';caption.querySelector('h2').textContent=s.title;caption.querySelector('p').textContent=s.subtitle;caption.classList.toggle('dark',s.dark===true);document.querySelector('.collection-status').textContent=(active+1)+' / '+entries.length;}
document.querySelectorAll('[data-collection]').forEach(b=>b.addEventListener('click',()=>showSlide(Number(b.dataset.collection))));
document.querySelector('.collection').addEventListener('keydown',e=>{if(e.key==='ArrowRight'||e.key==='ArrowLeft'){e.preventDefault();showSlide(e.key==='ArrowRight'?1:-1);}});
let collectionStart=null;document.querySelector('.collection').addEventListener('pointerdown',e=>{if(e.target.closest('button'))return;collectionStart={x:e.clientX,y:e.clientY};});document.querySelector('.collection').addEventListener('pointerup',e=>{if(!collectionStart)return;const x=e.clientX-collectionStart.x,y=e.clientY-collectionStart.y;collectionStart=null;if(Math.abs(x)>50&&Math.abs(x)>Math.abs(y)*1.5)showSlide(x<0?1:-1);});
const drawer=document.querySelector('.mobile-drawer'),shade=document.querySelector('.menu-shade'),toggle=document.querySelector('.menu-toggle');function closeMenu(restore=true){drawer.hidden=true;shade.hidden=true;toggle.setAttribute('aria-expanded','false');if(restore)toggle.focus();}toggle.addEventListener('click',()=>{drawer.hidden=false;shade.hidden=false;toggle.setAttribute('aria-expanded','true');drawer.querySelector('.drawer-close').focus();});drawer.querySelector('.drawer-close').addEventListener('click',()=>closeMenu());shade.addEventListener('click',()=>closeMenu());document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!drawer.hidden)closeMenu();});window.addEventListener('resize',()=>{if(innerWidth>767)closeMenu(false);});
document.querySelectorAll('a[href^="#"]').forEach(a=>a.addEventListener('click',e=>{const target=document.getElementById(a.hash.slice(1));if(!target)return;e.preventDefault();closeMenu(false);if(target.id==='top')window.scrollTo({top:0,behavior:reduced?'auto':'smooth'});else target.scrollIntoView({behavior:reduced?'auto':'smooth',block:'start'});history.replaceState(null,'',a.hash);const focus=[...target.querySelectorAll('h1,h2')].find(x=>x.getBoundingClientRect().width>0)||target;focus.setAttribute('tabindex','-1');focus.focus({preventScroll:true});}));
const demo=document.getElementById('demo-dialog');let opener=null;document.querySelectorAll('[data-demo]').forEach(b=>b.addEventListener('click',()=>{opener=b;demo.querySelector('h2').textContent=b.dataset.demo;demo.showModal();}));
const viewer=document.getElementById('photo-dialog');let photoOpener=null;document.querySelectorAll('[data-photo]').forEach(b=>b.addEventListener('click',()=>{photoOpener=b;viewer.querySelector('img').src=b.querySelector('img')?.currentSrc||b.dataset.photo;viewer.querySelector('img').alt=b.querySelector('img')?.alt||'서래커튼의 공간 연출 사진';viewer.querySelector('h2').textContent=b.dataset.title||'사진 보기';viewer.showModal();}));document.querySelectorAll('[data-close]').forEach(b=>b.addEventListener('click',()=>b.closest('dialog').close()));demo.addEventListener('close',()=>opener?.focus({preventScroll:true}));viewer.addEventListener('close',()=>photoOpener?.focus({preventScroll:true}));document.querySelectorAll('dialog').forEach(d=>d.addEventListener('click',e=>{if(e.target===d)d.close();}));
const search=document.getElementById('search-dialog');document.querySelector('[data-search]').addEventListener('click',()=>search.showModal());const input=search.querySelector('input');input.addEventListener('input',()=>{const q=input.value.trim().toLowerCase();const list=search.querySelector('.search-results');list.replaceChildren();entries.filter(s=>!q||(s.title+' '+(s.keywords||'')).toLowerCase().includes(q)).slice(0,6).forEach(s=>{const li=document.createElement('li'),a=document.createElement('a');a.href='#collection';a.textContent=s.title;a.addEventListener('click',e=>{e.preventDefault();active=entries.indexOf(s);showSlide(0);search.close();document.getElementById('collection').scrollIntoView({behavior:reduced?'auto':'smooth'});});li.append(a);list.append(li);});if(q&&!list.children.length){const li=document.createElement('li');li.textContent='검색 결과가 없습니다.';list.append(li);}});search.addEventListener('close',()=>document.querySelector('[data-search]').focus({preventScroll:true}));search.addEventListener('keydown',e=>{if(e.key==='Escape'){e.preventDefault();e.stopPropagation();search.close();}},true);
document.querySelectorAll('.gallery,.portfolio').forEach(region=>{const strip=region.querySelector('.gallery-strip');const move=delta=>strip.scrollBy({left:delta*(strip.querySelector('.gallery-card').getBoundingClientRect().width+parseFloat(getComputedStyle(strip).gap||0)),behavior:reduced?'auto':'smooth'});for(const [delta,name] of [[-1,'이전 사진'],[1,'다음 사진']]){const b=document.createElement('button');b.className='gallery-arrow '+(delta<0?'prev':'next');b.setAttribute('aria-label',name);const i=document.createElement('img');i.src='assets/ui54/chevron-'+(delta<0?'left':'right')+'.svg';i.alt='';b.append(i);b.addEventListener('click',()=>move(delta));region.append(b);}strip.addEventListener('keydown',e=>{if(e.key==='ArrowRight'||e.key==='ArrowLeft'){e.preventDefault();move(e.key==='ArrowRight'?1:-1);}});});
const playback=document.querySelector('.collection-playback');let collectionPaused=reduced;function updatePlayback(){playback.setAttribute('aria-pressed',String(collectionPaused));playback.setAttribute('aria-label',collectionPaused?'자동 사진 넘김 재생':'자동 사진 넘김 멈추기');playback.querySelector('.playback-label').textContent=collectionPaused?'자동 넘김 재생':'자동 넘김 멈추기';playback.querySelector('.playback-icon').textContent=collectionPaused?'▷':'Ⅱ';}updatePlayback();playback.addEventListener('click',()=>{collectionPaused=!collectionPaused;updatePlayback();});
let collectionVisible=false;new IntersectionObserver(rows=>{collectionVisible=rows[0].isIntersecting;},{threshold:.2}).observe(document.querySelector('.collection'));setInterval(()=>{const region=document.querySelector('.collection');if(!collectionPaused&&collectionVisible&&document.visibilityState==='visible'&&!region.matches(':hover,:focus-within')&&!document.querySelector('dialog[open]'))showSlide(1);},5500);

drawer.addEventListener('keydown',e=>{if(e.key!=='Tab')return;const all=[...drawer.querySelectorAll('button,a')].filter(x=>x.getBoundingClientRect().width>0);if(e.shiftKey&&document.activeElement===all[0]){e.preventDefault();all.at(-1).focus();}else if(!e.shiftKey&&document.activeElement===all.at(-1)){e.preventDefault();all[0].focus();}});

document.querySelectorAll('.drawer-expand').forEach(b=>b.addEventListener('click',()=>{const group=document.getElementById(b.getAttribute('aria-controls'));group.hidden=!group.hidden;b.setAttribute('aria-expanded',String(!group.hidden));}));
