const notes=JSON.parse(document.getElementById('note-data').textContent);
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
const menu=document.getElementById('site-menu'),menuButton=document.querySelector('.menu-toggle');
menuButton.addEventListener('click',()=>menu.showModal());menu.addEventListener('close',()=>menuButton.focus({preventScroll:true}));
document.querySelectorAll('[data-close]').forEach(b=>b.addEventListener('click',()=>b.closest('dialog').close()));
const story=document.getElementById('story-dialog');let storyOpener=null;
function openStory(id,opener){const n=notes.find(n=>n.id===id);if(!n)return;storyOpener=opener;if(menu.open)menu.close();story.querySelector('.story-category').textContent=n.category+' / VOL. 01';document.getElementById('story-title').textContent=n.title;story.querySelector('.story-lead').textContent=n.summary;story.querySelector('.story-photo').src='assets/'+n.image;story.querySelector('.story-photo').alt=n.alt;const body=story.querySelector('.story-body');body.replaceChildren();const p=document.createElement('p');p.textContent=n.text;body.append(p);story.showModal();story.scrollTop=0;}
document.querySelectorAll('[data-story]').forEach(b=>b.addEventListener('click',()=>openStory(b.dataset.story,b)));story.addEventListener('close',()=>{if(storyOpener?.closest('#site-menu')||!storyOpener?.isConnected)menuButton.focus({preventScroll:true});else storyOpener?.focus({preventScroll:true});});
const demo=document.getElementById('demo-dialog');let demoOpener=null;function openDemo(title,detail,opener){demoOpener=opener;document.getElementById('demo-title').textContent=title;demo.querySelector('.demo-detail').textContent=detail;demo.showModal();}demo.addEventListener('close',()=>demoOpener?.focus({preventScroll:true}));document.querySelectorAll('[data-demo]').forEach(b=>b.addEventListener('click',()=>openDemo(b.dataset.demo,b.dataset.demo==='협업 문의 준비'?'관심 있는 주제와 소개할 장면, 형식과 생각하는 시점을 정리해 보세요.':'이번 호의 음악과 손작업 기록을 페이지에서 읽어 보세요.',b)));
document.querySelector('[data-newsletter]').addEventListener('submit',e=>{e.preventDefault();e.currentTarget.reset();openDemo('알림 신청 안내','신청 화면을 확인했습니다. 이메일을 저장하거나 실제 알림을 발송하지 않습니다.',e.currentTarget.querySelector('button'));});
document.querySelectorAll('a[href^="#"]').forEach(a=>a.addEventListener('click',e=>{const target=document.getElementById(a.hash.slice(1));if(!target)return;e.preventDefault();if(menu.open)menu.close();if(target.id==='top')window.scrollTo({top:0,behavior:reduced?'auto':'smooth'});else target.scrollIntoView({behavior:reduced?'auto':'smooth'});history.replaceState(null,'',a.hash);const heading=target.querySelector('h1,h2')||target;heading.setAttribute('tabindex','-1');heading.focus({preventScroll:true});}));
const coverItems=[{image:'cover-v56.webp',alt:'수집노트 음악과 손작업 표지, 도자기 컵을 든 가상 인물'},{image:'issue-cover-v19.webp',alt:'파란 바탕의 음반과 도자기 컵'},{image:'studio-v56.webp',alt:'음악과 도자기가 함께 놓인 작업실'}];let coverIndex=0;function moveCover(delta){coverIndex=(coverIndex+delta+coverItems.length)%coverItems.length;const item=coverItems[coverIndex],img=document.querySelector('.cover-image');img.src='assets/'+item.image;img.alt=item.alt;document.querySelector('.cover-count').textContent=(coverIndex+1)+' / '+coverItems.length;}
document.querySelector('.cover-prev').addEventListener('click',()=>moveCover(-1));document.querySelector('.cover-next').addEventListener('click',()=>moveCover(1));const cover=document.querySelector('.cover-carousel');cover.addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();moveCover(e.key==='ArrowRight'?1:-1);}});let start=null;cover.addEventListener('pointerdown',e=>{if(e.target.closest('button'))return;start=[e.clientX,e.clientY];});cover.addEventListener('pointerup',e=>{if(!start)return;const dx=e.clientX-start[0],dy=e.clientY-start[1];start=null;if(Math.abs(dx)>40&&Math.abs(dx)>Math.abs(dy)*1.5)moveCover(dx<0?1:-1);});cover.addEventListener('pointercancel',()=>start=null);
const darkFeatureIds=new Set(['record','choose','clay','objects']);let featureIndex=notes.findIndex(n=>n.id==='studio');function showFeature(index){featureIndex=(index+notes.length)%notes.length;const n=notes[featureIndex],img=document.querySelector('.feature-image');img.src='assets/'+n.image;img.alt=n.alt;const b=document.querySelector('.feature-copy button');b.dataset.story=n.id;b.textContent=n.title;document.querySelector('.feature-copy p').textContent=n.summary;document.querySelector('.feature-kicker').textContent=n.category+' / VOL. 01';document.querySelector('.feature-index').textContent=String(featureIndex+1).padStart(2,'0')+' / '+String(notes.length).padStart(2,'0');document.querySelectorAll('[data-feature]').forEach(x=>{const selected=x.dataset.feature===n.id;x.classList.toggle('is-active',selected);x.setAttribute('aria-pressed',String(selected));});updateChrome();}document.querySelectorAll('[data-feature]').forEach(b=>b.addEventListener('click',()=>showFeature(notes.findIndex(n=>n.id===b.dataset.feature))));document.querySelectorAll('[data-feature-step]').forEach(b=>b.addEventListener('click',()=>showFeature(featureIndex+Number(b.dataset.featureStep))));showFeature(featureIndex);
function renderResults(container,items){container.replaceChildren();if(!items.length){const p=document.createElement('p');p.textContent='찾은 기록이 없습니다.';container.append(p);return;}items.forEach(n=>{const b=document.createElement('button');b.textContent=n.title;b.addEventListener('click',()=>openStory(n.id,b));container.append(b);});}
const search=document.querySelector('.menu-search');search.addEventListener('submit',e=>{e.preventDefault();const query=search.querySelector('input').value.trim().toLowerCase();renderResults(document.querySelector('.menu-results'),notes.filter(n=>(n.title+' '+n.category+' '+n.summary).toLowerCase().includes(query)));});menu.addEventListener('keydown',e=>{if(e.key==='Escape'){e.preventDefault();e.stopPropagation();menu.close();}},true);
document.querySelectorAll('[data-category]').forEach(b=>b.addEventListener('click',e=>{e.preventDefault();const cat=b.dataset.category,items=notes.filter(n=>cat==='전체'||n.category===cat);const box=document.querySelector('.archive-results');box.hidden=false;renderResults(box,items);if(menu.open)menu.close();document.getElementById('archive').scrollIntoView({behavior:reduced?'auto':'smooth'});box.setAttribute('tabindex','-1');box.focus({preventScroll:true});}));
document.querySelectorAll('.card-strip').forEach(strip=>strip.addEventListener('keydown',e=>{if(e.key==='ArrowRight'||e.key==='ArrowLeft'){e.preventDefault();strip.scrollBy({left:(e.key==='ArrowRight'?1:-1)*(strip.querySelector('.journal-card').getBoundingClientRect().width+20),behavior:reduced?'auto':'smooth'});}}));
function updateChrome(){document.querySelector('.reading-bar').hidden=window.scrollY<500;const y=40;const featureRect=document.querySelector('.feature-hero').getBoundingClientRect();const dark=(darkFeatureIds.has(notes[featureIndex].id)&&featureRect.top<=y&&featureRect.bottom>y)||[...document.querySelectorAll('.wide-banner>img,.large-story>img,.paired-stories img,footer')].some(e=>{const r=e.getBoundingClientRect();return r.top<=y&&r.bottom>y;});menuButton.classList.toggle('on-dark',dark);}document.addEventListener('scroll',updateChrome,{passive:true});window.addEventListener('resize',updateChrome);updateChrome();

const featureRegion=document.querySelector('.feature-hero');let featureStart=null;featureRegion.addEventListener('pointerdown',e=>{if(e.target.closest('button'))return;featureStart=[e.clientX,e.clientY];});featureRegion.addEventListener('pointerup',e=>{if(!featureStart)return;const dx=e.clientX-featureStart[0],dy=e.clientY-featureStart[1];featureStart=null;if(Math.abs(dx)>50&&Math.abs(dx)>Math.abs(dy)*1.5)showFeature(featureIndex+(dx<0?1:-1));});featureRegion.addEventListener('pointercancel',()=>featureStart=null);
